<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

/**
 * Writes the database template as plain Postgres (Supabase) statements, straight from the migrations.
 * No database connection is needed, so anyone can regenerate it after changing a migration.
 */
class DumpSchemaSql extends Command
{
    protected $signature = 'schema:sql {path=database/schema/zb_ideas.postgres.sql}';

    protected $description = 'Write an empty-database Postgres template for Supabase (tables and row level security, no data)';

    public function handle(): int
    {
        config(['database.default' => 'pgsql', 'database.connections.pgsql.database' => 'postgres']);
        DB::purge('pgsql');
        // A Postgres-flavoured connection backed by a throwaway PDO: statements are built by the Postgres grammar but never executed.
        DB::extend('pgsql', fn () => new \Illuminate\Database\PostgresConnection(new \PDO('sqlite::memory:'), 'postgres'));

        $out = [
            '-- ZB Idea Manager: empty database template for Supabase (Postgres)',
            '-- Generated by `php artisan schema:sql` from database/migrations. Tables only, no data.',
            '-- Run it once in the Supabase SQL editor on an empty project. Do not also run `php artisan migrate`.',
            '',
        ];
        $tables = [];

        foreach (collect(File::files(database_path('migrations')))->sortBy(fn ($f) => $f->getFilename()) as $file) {
            $migration = require $file->getPathname();
            $statements = DB::connection('pgsql')->pretend(fn () => $migration->up());
            $out[] = '-- '.$file->getFilename();
            foreach ($statements as $s) {
                $sql = $this->inline($s['query'], $s['bindings']);
                if (preg_match('/^create table "([^"]+)"/i', $sql, $m)) {
                    $tables[] = $m[1];
                }
                $out[] = $sql.';';
            }
            $out[] = '';
        }

        $out[] = '-- Row level security: Supabase exposes public tables through its REST API. Enabling RLS with no policies';
        $out[] = '-- keeps the data private; Laravel connects as the postgres role, which bypasses RLS.';
        foreach ($tables as $t) {
            $out[] = 'alter table "'.$t.'" enable row level security;';
        }
        $out[] = '';
        $out[] = '-- Tell Laravel the migrations are already applied (so a later `php artisan migrate` does nothing).';
        $out[] = 'create table if not exists "migrations" ("id" serial primary key, "migration" varchar(255) not null, "batch" integer not null);';
        foreach (collect(File::files(database_path('migrations')))->sortBy(fn ($f) => $f->getFilename()) as $file) {
            $out[] = 'insert into "migrations" ("migration", "batch") values (\''.pathinfo($file->getFilename(), PATHINFO_FILENAME).'\', 1);';
        }
        $out[] = '';

        File::ensureDirectoryExists(dirname(base_path($this->argument('path'))));
        File::put(base_path($this->argument('path')), implode("\n", $out));
        $this->info('Wrote '.$this->argument('path'));

        return self::SUCCESS;
    }

    private function inline(string $sql, array $bindings): string
    {
        foreach ($bindings as $b) {
            $sql = preg_replace('/\?/', is_numeric($b) ? (string) $b : "'".str_replace("'", "''", (string) $b)."'", $sql, 1);
        }

        return $sql;
    }
}
