-- ZB Idea Manager: empty database template for Supabase (Postgres)
-- Generated by `php artisan schema:sql` from database/migrations. Tables only, no data.
-- Run it once in the Supabase SQL editor on an empty project. Do not also run `php artisan migrate`.

-- 0001_01_01_000000_create_users_table.php
create table "users" ("id" bigserial not null primary key, "name" varchar(255) not null, "email" varchar(255) not null, "email_verified_at" timestamp(0) without time zone null, "password" varchar(255) null, "title" varchar(255) null, "dept" varchar(255) null, "bio" text null, "joined" varchar(8) null, "is_admin" boolean not null default '0', "color" varchar(9) not null default '#049016', "avatar_path" varchar(255) null, "phone" varchar(20) null, "whatsapp_opt_in" boolean not null default '1', "remember_token" varchar(100) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "users" add constraint "users_email_unique" unique ("email");
alter table "users" add constraint "users_phone_unique" unique ("phone");
create table "password_reset_tokens" ("email" varchar(255) not null, "token" varchar(255) not null, "created_at" timestamp(0) without time zone null);
alter table "password_reset_tokens" add primary key ("email");
create table "sessions" ("id" varchar(255) not null, "user_id" bigint null, "ip_address" varchar(45) null, "user_agent" text null, "payload" text not null, "last_activity" integer not null);
alter table "sessions" add primary key ("id");
create index "sessions_user_id_index" on "sessions" ("user_id");
create index "sessions_last_activity_index" on "sessions" ("last_activity");

-- 0001_01_01_000001_create_cache_table.php
create table "cache" ("key" varchar(255) not null, "value" text not null, "expiration" bigint not null);
alter table "cache" add primary key ("key");
create index "cache_expiration_index" on "cache" ("expiration");
create table "cache_locks" ("key" varchar(255) not null, "owner" varchar(255) not null, "expiration" bigint not null);
alter table "cache_locks" add primary key ("key");
create index "cache_locks_expiration_index" on "cache_locks" ("expiration");

-- 0001_01_01_000002_create_jobs_table.php
create table "jobs" ("id" bigserial not null primary key, "queue" varchar(255) not null, "payload" text not null, "attempts" smallint not null, "reserved_at" integer null, "available_at" integer not null, "created_at" integer not null);
create index "jobs_queue_index" on "jobs" ("queue");
create table "job_batches" ("id" varchar(255) not null, "name" varchar(255) not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text null, "cancelled_at" integer null, "created_at" integer not null, "finished_at" integer null);
alter table "job_batches" add primary key ("id");
create table "failed_jobs" ("id" bigserial not null primary key, "uuid" varchar(255) not null, "connection" varchar(255) not null, "queue" varchar(255) not null, "payload" text not null, "exception" text not null, "failed_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP);
create index "failed_jobs_connection_queue_failed_at_index" on "failed_jobs" ("connection", "queue", "failed_at");
alter table "failed_jobs" add constraint "failed_jobs_uuid_unique" unique ("uuid");

-- 2026_10_01_000000_create_idea_manager_tables.php
create table "login_codes" ("id" bigserial not null primary key, "email" varchar(255) not null, "code_hash" varchar(255) not null, "attempts" smallint not null default '0', "expires_at" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create index "login_codes_email_index" on "login_codes" ("email");
create table "challenges" ("id" bigserial not null primary key, "user_id" bigint not null, "title" varchar(255) not null, "brief" text not null, "keywords" json not null, "deadline" date null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "challenges" add constraint "challenges_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
create table "ideas" ("id" bigserial not null primary key, "num" integer not null, "user_id" bigint not null, "challenge_id" bigint null, "title" varchar(255) not null, "summary" text not null, "body" text not null, "status" varchar(16) not null default 'Idea', "approved" boolean not null default '0', "approved_by" bigint null, "approved_at" timestamp(0) without time zone null, "approval_note" text null, "shares" integer not null default '0', "source" varchar(12) not null default 'web', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "ideas" add constraint "ideas_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "ideas" add constraint "ideas_challenge_id_foreign" foreign key ("challenge_id") references "challenges" ("id") on delete set null;
alter table "ideas" add constraint "ideas_approved_by_foreign" foreign key ("approved_by") references "users" ("id") on delete set null;
alter table "ideas" add constraint "ideas_num_unique" unique ("num");
create index "ideas_status_index" on "ideas" ("status");
create table "idea_likes" ("idea_id" bigint not null, "user_id" bigint not null);
alter table "idea_likes" add constraint "idea_likes_idea_id_foreign" foreign key ("idea_id") references "ideas" ("id") on delete cascade;
alter table "idea_likes" add constraint "idea_likes_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "idea_likes" add primary key ("idea_id", "user_id");
create table "idea_saves" ("idea_id" bigint not null, "user_id" bigint not null);
alter table "idea_saves" add constraint "idea_saves_idea_id_foreign" foreign key ("idea_id") references "ideas" ("id") on delete cascade;
alter table "idea_saves" add constraint "idea_saves_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "idea_saves" add primary key ("idea_id", "user_id");
create table "comments" ("id" bigserial not null primary key, "idea_id" bigint not null, "user_id" bigint not null, "body" text not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "comments" add constraint "comments_idea_id_foreign" foreign key ("idea_id") references "ideas" ("id") on delete cascade;
alter table "comments" add constraint "comments_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
create table "idea_files" ("id" bigserial not null primary key, "idea_id" bigint not null, "kind" varchar(8) not null default 'doc', "name" varchar(255) not null, "path" varchar(255) null, "size" varchar(16) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "idea_files" add constraint "idea_files_idea_id_foreign" foreign key ("idea_id") references "ideas" ("id") on delete cascade;
create table "conversations" ("id" bigserial not null primary key, "user_a" bigint not null, "user_b" bigint not null, "last_message_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "conversations" add constraint "conversations_user_a_foreign" foreign key ("user_a") references "users" ("id") on delete cascade;
alter table "conversations" add constraint "conversations_user_b_foreign" foreign key ("user_b") references "users" ("id") on delete cascade;
alter table "conversations" add constraint "conversations_user_a_user_b_unique" unique ("user_a", "user_b");
create table "messages" ("id" bigserial not null primary key, "conversation_id" bigint not null, "user_id" bigint not null, "body" text not null, "read_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "messages" add constraint "messages_conversation_id_foreign" foreign key ("conversation_id") references "conversations" ("id") on delete cascade;
alter table "messages" add constraint "messages_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
create table "activities" ("id" bigserial not null primary key, "user_id" bigint not null, "type" varchar(16) not null, "actor_id" bigint null, "idea_id" bigint null, "challenge_id" bigint null, "note" text null, "read_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "activities" add constraint "activities_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "activities" add constraint "activities_actor_id_foreign" foreign key ("actor_id") references "users" ("id") on delete set null;
alter table "activities" add constraint "activities_idea_id_foreign" foreign key ("idea_id") references "ideas" ("id") on delete cascade;
alter table "activities" add constraint "activities_challenge_id_foreign" foreign key ("challenge_id") references "challenges" ("id") on delete cascade;
create table "sent_emails" ("id" bigserial not null primary key, "type" varchar(16) not null, "to" varchar(255) not null, "from" varchar(255) not null, "subject" varchar(255) not null, "body" text not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "whatsapp_sessions" ("id" bigserial not null primary key, "phone" varchar(20) not null, "user_id" bigint null, "state" varchar(24) not null default 'idle', "draft" json null, "pending_email" varchar(255) null, "last_inbound_at" timestamp(0) without time zone null, "locked_until" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "whatsapp_sessions" add constraint "whatsapp_sessions_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete set null;
alter table "whatsapp_sessions" add constraint "whatsapp_sessions_phone_unique" unique ("phone");
create table "whatsapp_messages" ("id" bigserial not null primary key, "wa_id" varchar(255) null, "phone" varchar(20) not null, "direction" varchar(3) not null, "intent" varchar(24) null, "status" varchar(12) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "whatsapp_messages" add constraint "whatsapp_messages_wa_id_unique" unique ("wa_id");
create index "whatsapp_messages_phone_index" on "whatsapp_messages" ("phone");

-- 2026_10_02_000000_enable_row_level_security.php

-- 2026_10_03_000000_use_zb_brand_green.php
update "users" set "color" = '#049016' where "color" = '#0d4a36';
alter table "users" alter column "color" type varchar(9), alter column "color" set not null, alter column "color" set default '#049016', alter column "color" drop identity if exists;
comment on column "users"."color" is NULL;

-- Row level security: Supabase exposes public tables through its REST API. Enabling RLS with no policies
-- keeps the data private; Laravel connects as the postgres role, which bypasses RLS.
alter table "users" enable row level security;
alter table "password_reset_tokens" enable row level security;
alter table "sessions" enable row level security;
alter table "cache" enable row level security;
alter table "cache_locks" enable row level security;
alter table "jobs" enable row level security;
alter table "job_batches" enable row level security;
alter table "failed_jobs" enable row level security;
alter table "login_codes" enable row level security;
alter table "challenges" enable row level security;
alter table "ideas" enable row level security;
alter table "idea_likes" enable row level security;
alter table "idea_saves" enable row level security;
alter table "comments" enable row level security;
alter table "idea_files" enable row level security;
alter table "conversations" enable row level security;
alter table "messages" enable row level security;
alter table "activities" enable row level security;
alter table "sent_emails" enable row level security;
alter table "whatsapp_sessions" enable row level security;
alter table "whatsapp_messages" enable row level security;

-- Tell Laravel the migrations are already applied (so a later `php artisan migrate` does nothing).
create table if not exists "migrations" ("id" serial primary key, "migration" varchar(255) not null, "batch" integer not null);
insert into "migrations" ("migration", "batch") values ('0001_01_01_000000_create_users_table', 1);
insert into "migrations" ("migration", "batch") values ('0001_01_01_000001_create_cache_table', 1);
insert into "migrations" ("migration", "batch") values ('0001_01_01_000002_create_jobs_table', 1);
insert into "migrations" ("migration", "batch") values ('2026_10_01_000000_create_idea_manager_tables', 1);
insert into "migrations" ("migration", "batch") values ('2026_10_02_000000_enable_row_level_security', 1);
insert into "migrations" ("migration", "batch") values ('2026_10_03_000000_use_zb_brand_green', 1);
